### ISSUE TITLE
Fallo con conexiones lentas

### ISSUE THREAD

**Issue by ignaciomartinCFR** [Bitbloq/QSSWeb2Board#26]
En un equipo con una conexión a internet de baja velocidad, no se puede programar desde bitbloq.
En el syslog aparece un timeout a los 20 segundos de cada Qurl ¿Se puede aumentar?

`

Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Message ID:  1
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Versions file  "/opt/QSSWeb2Board/res/arduino/libraries/versions.json"
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: "https://api.github.com/repos/bitbloq/bitbloqLibs/releases/latest"
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: No version.json file
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Updating bitbloq libraries to new version
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Temp Dir:  "/opt/QSSWeb2Board/tmp/"
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Downloading  QUrl("https://api.github.com/repos/Bitbloq/bitbloqLibs/zipball/1.7.0")
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: waiting to finish...
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: No version.json file
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Updating bitbloq libraries to new version
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Temp Dir:  "/opt/QSSWeb2Board/tmp/"
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: Downloading  QUrl("https://api.github.com/repos/Bitbloq/bitbloqLibs/zipball/1.7.0")
Sep  4 13:38:00 cliente-3 QSSWeb2Board-handler.desktop[5472]: waiting to finish...
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: finished!
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: Downloading  QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: waiting to finish...
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: finished!
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: Downloading  QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:38:01 cliente-3 QSSWeb2Board-handler.desktop[5472]: waiting to finish...
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: finished!
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: finished!
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: QUrl("")
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: QUrl("")
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: TimeOut Downloading Libs
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: TimeOut Downloading Libs
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: Failure:  "set_lib_version"
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: "TimeOut Downloading Libs"
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: Failure:  "set_lib_version"
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: "TimeOut Downloading Libs"
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: "TimeOut Downloading Libs"
Sep  4 13:38:21 cliente-3 QSSWeb2Board-handler.desktop[5472]: "TimeOut Downloading Libs"
`

En el mismo equipo, pero esta vez saliendo por una conexión a internet mejor sí va:

`
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Message ID:  1
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Message ID:  1
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Versions file  "/opt/QSSWeb2Board/res/arduino/libraries/versions.json"
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Versions file  "/opt/QSSWeb2Board/res/arduino/libraries/versions.json"
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: "https://api.github.com/repos/bitbloq/bitbloqLibs/releases/latest"
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: "https://api.github.com/repos/bitbloq/bitbloqLibs/releases/latest"
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: No version.json file
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Updating bitbloq libraries to new version
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Temp Dir:  "/opt/QSSWeb2Board/tmp/"
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Downloading  QUrl("https://api.github.com/repos/Bitbloq/bitbloqLibs/zipball/1.7.0")
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: waiting to finish...
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: No version.json file
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Updating bitbloq libraries to new version
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Temp Dir:  "/opt/QSSWeb2Board/tmp/"
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: Downloading  QUrl("https://api.github.com/repos/Bitbloq/bitbloqLibs/zipball/1.7.0")
Sep  4 13:55:31 cliente-3 QSSWeb2Board-handler.desktop[2501]: waiting to finish...
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: finished!
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: Downloading  QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: waiting to finish...
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: finished!
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: Downloading  QUrl("https://codeload.github.com/Bitbloq/bitbloqLibs/legacy.zip/1.7.0")
Sep  4 13:55:32 cliente-3 QSSWeb2Board-handler.desktop[2501]: waiting to finish...
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: finished!
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: finished!
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: QUrl("")
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: QUrl("")
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: "Saving to /opt/QSSWeb2Board/tmp/bitbloqLibs.zip"
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: "Saving to /opt/QSSWeb2Board/tmp/bitbloqLibs.zip"
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: Done
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: Done
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: "unzip -o /opt/QSSWeb2Board/tmp/bitbloqLibs.zip -d /opt/QSSWeb2Board/tmp/"
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: "unzip -o /opt/QSSWeb2Board/tmp/bitbloqLibs.zip -d /opt/QSSWeb2Board/tmp/"
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: exit Code 0
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: exit Code 0
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: Succesfully Unzipped
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: TEMP DIR  "/opt/QSSWeb2Board/tmp/Bitbloq-bitbloqLibs-9968f7d"
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: Removing former libs version  "/opt/QSSWeb2Board/res/arduino/libraries/"
Sep  4 13:55:42 cliente-3 QSSWeb2Board-handler.desktop[2501]: Succesfully Unzipped`

**Comment by avalero** [comment]
Estamos hablando de descargar apenas 100K, si en 20 segundos no lo ha descargado es que muuuuuuy lenta. En cualquier caso, ¿para qué sistema operativo es? Os puedo preparar un instalador con un timeout mayor.

**Comment by ignaciomartinCFR** [comment]
En los centros más rurales tenemos conexión por 3G / 4G. Son unos 300 KB/s a repartir entre varios equipos. 
El SO es debian stretch.

* Si las url que aparecen en el log son correctas son algunos megas, por ejemplo:

`
$ wget https://api.github.com/repos/Bitbloq/bitbloqLibs/zipball/1.7.0
--2018-09-05 07:58:31--  https://api.github.com/repos/Bitbloq/bitbloqLibs/zipball/1.7.0
Grabando a: “1.7.0”
1.7.0                                  [                              <=>                                        ]   2,29M  53,4KB/s    en 45s     
2018-09-05 07:59:17 (52,6 KB/s) - “1.7.0” guardado [2398395]
`

**Comment by avalero** [comment]
Ya tienes los instaladores con timeout de 40 segundos para los OS oficiales (entre los que no está debian) Vuestro debían es 32 o 64 bits?

**Comment by avalero** [comment]
En cuanto podamos preparamos un instalador para vosotros.

Sobre la desinstalación es normal que te diga eso, ya que en ese directorio se guardan las actualizaciones de las librerías de bitbloq por lo que al haber sido modificado después de la instalación lo mantiene.

**Comment by avalero** [comment]
Hola.

Ese es un problema de g++, no de QSSWeb2Board. Parecería que la versión de debian que utilizas tiene un g++ anticuado que no incluye los últimos modelos de micros de atmel.

En cualquier caso, cuanto tengamos el instalador de debian lo pruebas por si el problema fuera otro.

**Comment by ignaciomartinCFR** [comment]
Hola,
Es extraño porque con la versión de ayer y una conexión rápida sí compilaba y programaba la placa: 
https://pastebin.com/EWpCZ7z3

Gracias, esperamos la versión debian

**Comment by avalero** [comment]
Hola,

Efectivamente, tras comprobar en debian 9.5 32 bits te confirmamos que la versión g++ del sistema no es compatible con Web2Board.

Puedes trabajar en Ubuntu 16.04 o 18.04 o bien trabajar con la compilación en línea.

Un saludo

**Comment by ignaciomartinCFR** [comment]
Hola,

Lamento insistir pero no es así.

Podemos compilar y programar con la versión del paquete deb que había ayer por la mañana.
Esta, la dejé aquí para las pruebas: http://repositorio.consorciofernandodelosrios.net/descargas/qssweb2board_3.0.0Ubuntu16.04_i386.deb

Aquí tienes el log de una prueba de ahora mismo. Compilando y programando dos códigos distintos, todo va bien:
https://pastebin.com/AF250BDS

El problema viene cuando se sobrepasan los 20 segundos en la descarga.

En cambio con la versión del paquete deb de hoy ocurre lo que te comentaba antes:
Estos son los mensajes: https://pastebin.com/cD29G03t
Y no aparece el mensaje de que esté actualizando las librerías la primera vez, parece que se salta ese paso.
Aunque he desinstalado el paquete y borrado el /opt/QSSWeb2Board

**Comment by avalero** [comment]
Entiendo que estás probando con el instalador de Unbutu 16.04 32 bits.
Prueba ahora. Hemos cambiado una cosa que podía ser la causa del problema.

**Comment by avalero** [comment]
Te hemos hecho un instalador para Debian 9.5 32 bits con un timeout de 90 segundos. Lo encuentras aquí: https://github.com/Bitbloq/QSSWeb2Board/releases/download/3.0.0/installer-qssweb2board_3.0.0DEBIAN9.5_i386.zip

**Comment by ignaciomartinCFR** [comment]
Muchas gracias Alberto.

Todo funciona perfecto, vamos a actualizar nuestros equipos con ese paquete.
