### ISSUE TITLE
CP210x USB to UART Bridge Driver Installer x64 fails for bq (silabnm) and Arduino LLC on Windows 10

### ISSUE THREAD

**Issue by ATmbaumgartner** [Bitbloq/QSSWeb2Board#33]
Hi,

I'm facing an issue on Windows 10 when installing the latest QSS Web2Board Package. I downloaded the package directly from github. The device I try to run is a Zowi. The installer stops with two install failures (screenshot).

![image](https://user-images.githubusercontent.com/43493551/45916065-07b15480-be60-11e8-95b5-725fd5d1daf0.png)

Can you please look into this?

Best,
Markus

**Comment by avalero** [comment]
Thanks. Drivers are gotten from provider. Unfortunatelly this is not a QSSWeb2Board issue.
