### ISSUE TITLE
Fallo al descargar actualización

### ISSUE THREAD

**Issue by ignaciomartinCFR** [Bitbloq/QSSWeb2Board#34]
Buenas,

Desde hace unos días al intentar programar en bitbloq aparece el mensaje siguiente:

"No tienes permisos de escritura en la instalación de Web2board. [..] Si estás en linux o MAC añade al usuario al grupo qssweb2board"

Verificamos que el usuario pertenece al grupo "qssweb2board", pero los directorios por debajo de
/opt/QSSWeb2Board/tmp no tienen permisos que permitan escribir. Tienen de usuario y grupo el primer usuario que ejecutó la aplicación, sin permiso de escritura para grupo ni otros. Cualquier otro usuario que no sea el primero no puede actualizar:

cd /opt/QSSWeb2Board/tmp/
# ls -lha
total 20K
drwxrwxr-x 5 root          qssweb2board  4,0K oct 31 19:57 .
drwxr-xr-x 4 root          qssweb2board  4,0K sep  6 08:32 ..
drwxr-xr-x 2 lolioliver989 lolioliver989 4,0K oct 31 19:57 build
drwxr-xr-x 6 dinamizador   dinamizador   4,0K sep  6 09:14 build1
drwxr-xr-x 5 dinamizador   dinamizador   4,0K sep  6 09:14 sketches

![captura de pantalla de 2018-11-02 08-52-57](https://user-images.githubusercontent.com/23031252/47904886-0a06c580-de86-11e8-8e35-8d3b7eacce74.png)
![captura de pantalla de 2018-11-02 08-52-41](https://user-images.githubusercontent.com/23031252/47904887-0a06c580-de86-11e8-966c-854130f2eff6.png)

**Comment by avalero** [comment]
Gracias por el informe de error. Lo analizamos y lo corregimos en la mayor brevedad.

**Comment by ignaciomartinCFR** [comment]
Perfecto, al actualizar se corrige. He intentado reproducir el problema pero ya no ocurre.

Gracias @avalero
