### ISSUE TITLE
Generación ISO 

### ISSUE THREAD

**Issue by joroca** [Bitbloq/QSSWeb2Board#35]
En el script postinst se crea el grupo qssweb2board con gid 1000. Cuando generamos una iso con este paquete incluido en nuestra distro, no se crea el usuario live porque ya existe un gid 1000, perteneciente al grupo qssweb2board. ¿ Es posible crear este grupo como un grupo de sistema añadiendo la opción --system al comando addgroup ?

addgroup --system qssweb2board

**Comment by ignaciomartinCFR** [comment]
Buenas @avalero , es un tema que necesitamos para la nueva versión del sistema operativo que tendremos en los centros Guadalinfo. Te agradezco la atención que acostumbras prestarnos.
Saludos

**Comment by avalero** [comment]
Hola. Sin problema. Modifico el postinst con esa opción. En cualquier caso, para el futuro, sentíos libres de hacer Pull Request con las modificaciones que consideréis oportunas.

**Comment by avalero** [comment]
https://github.com/Bitbloq/QSSWeb2Board/commit/91ba3ad0650acfdd983138b7176c80d1694d4c88
