### ISSUE TITLE
Debian packaging errors

### ISSUE THREAD

**Issue by mariodebian** [Bitbloq/QSSWeb2Board#36]
Hi, I'm Mario Izquierdo, one of MAX devs.

I'm trying to put QSSWeb2Board in our repo and get this error:

```
$ reprepro  --ask-passphrase -b . -V -C main includedeb max qssweb2board_3.0.0MAX10.0_amd64.deb 
Character 0x51 not allowed in package name: 'QSSWeb2Board'!
To ignore use --ignore=forbiddenchar.
There have been errors!
```

* Debian package names must be in lowercase letters
* Debian package names should contain a /usr/share/doc/${PACKAGENAME}/changelog.gz
* Should remove users/groups and dirs (created on install) during the uninstall

We use sbuild for package building (in a clean chroot), something like sbuild/pbuilder is better than "dpkg --build"

**Comment by avalero** [comment]
Hi.
We have updated the Max 10.0 installer. Please, download the zip and check de debian .deb file inside.
We have not bee able to test it ourselves with our commands as we lack the ./conf/distribution file
