### ISSUE TITLE
Certificado ssl web2board.es caducado

### ISSUE THREAD

**Issue by ignaciomartinCFR** [Bitbloq/QSSWeb2Board#37]
Muy buenas,

El certificado www.web2board.es.crt de la 3.5.0 está caducado del pasado 12 julio.
El navegador no conecta a la aplicación por este motivo.

¿Vais a renovarlo y generar nuevo paquete (en nuestro caso usamos el de Ubuntu 16.04 **32** bits? 
¿O tiene otra solución?

Gracias!

**Comment by avalero** [comment]
Hola,

Hemos actualizado los instaladores de Ubuntu 16.04 con el nuevo certificado SSL. Instalalo y nos dices si va bien

**Comment by ignaciomartinCFR** [comment]
Sí, funciona.
Gracias!
